version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to s3
          command: |
            aws s3 cp index.html *.asc s3://tsoporan.com

workflows:
  version: 2
  do-deploy:
    jobs:
      - deploy
